import {useEffect, useState} from "react";

export const useBooks = () => {

    const [books, setBooks] = useState([]);
    /**
     * Se hace uso de useEffect para definir un efecto de montaje que traerá la información de los libros
     * del back-end en el primer renderizado.
     */
    useEffect(() => {
        setTimeout(() => {
            setBooks([
                {id: "1", nombre: "Nada que decir", autor: "Silvia Hidalgo", anoPublicacion: 2023, isbn: 9788411073417, portada:"https://covers.feedbooks.net/item/5650583.jpg?size=large&t=1697156483", sinopsis: "Una mujer aguarda en el interior de un coche a que su exmarido recoja a la hija de ambos, que llora en el asiento de atrás. Mientras cae la lluvia y las figuras se desdibujan iluminadas por los intermitentes, ella está pendiente de su móvil y de una cita con un desconocido. Como un animal desorientado y furioso, se deja llevar por su deseo crudo, sin tapujos, en el que la maternidad, la familia, el trabajo ocupan un lugar secundario. Quiere huir de los espejismos de una falsa felicidad, pero se sitúa ante el abismo de una relación enfermiza, desquiciada, con un directivo de la empresa de su exmarido, un «hombre tumor».", critica: 3.5},
                {id: "2", nombre: "El infiltrado", autor: "John le Carré", anoPublicacion: 2016, isbn: 9788408154983, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/764f1825-01f5-4989-4432-2515b2600400/default", sinopsis: "Al comienzo, Jonathan Pine es simplemente el director nocturno de un lujoso hotel. Pero, cuando un intento de pasar información acerca de un hombre de negocios internacionales con tratos sospechosos alojado e n el establecimiento se vuelve en su contra de una manera terrible y empiezan a morir personas cercanas a Pine, él se compromete a luchar contra unas fuerzas tan poderosas que no podría ni imaginar. En un relato escalofriante sobre corruptas agencias de inteligencia, sumas millonarias y la verdad tras el brutal comercio de armas, John le Carré crea un mundo claustrofóbico en el que no se puede confiar en nadie.", critica: 3.67},
                {id: "3", nombre: "One Piece nº 001", autor: "Eiichiro Oda", anoPublicacion: 2022, isbn: 9788468471525, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/cfebd578-f0d0-4cc0-7c37-0c4aae09bc00/default", sinopsis: "Sigue las aventuras de Monkey D. Luffy, un chico muy especial y elástico, que sueña con ser el rey de los piratas y encontrar una gran tesoro: el One Piece. Para ello, se hace a la mar en un bote con el que buscará la tripulación que le pueda ayudar en su misión.\n" +
                        "Uno de los manga shônen más exitosos de la Historia, junto con Dragon Ball y Naruto. El argumento destaca valores como el espíritu superación, la tolerancia hacia la diferencia y el compañerismo. Creado por el mangaka Eiichiro Oda.", critica: 4.2},
                {id: "4", nombre: "Angélique", autor: "Guillaume Musso", anoPublicacion: 2023, isbn: 9788411484213, portada:"https://covers.feedbooks.net/item/5692280.jpg?size=large&t=1698451804", sinopsis: "Un laberinto de emociones e incertidumbres del autor más vendido de Francia.Incluso los ángeles tienen sus demonios...París, Navidad de 2021.Tras sufrir un ataque al corazón, Mathias Taillefer se despierta en una habitación de hospital. A su cabecera está una joven desconocida. Se trata de Louise Collange, una estudiante que toca el violonchelo para los pacientes de forma desinteresada. Al enterarse de que Mathias es policía, le pide que retome un caso un tanto particular. Aunque al principio se resiste, Mathias acaba accediendo a prestarle ayuda y desde ese momento ambos quedan atrapados en un engranaje mortal.Así comienza una investigación fuera de lo común, cuyo secreto reside en la vida que nos habría gustado tener, el amor que podríamos haber conocido y el lugar que todavía esperamos encontrar en el mundo...", critica: 4.2},
                {id: "5", nombre: "Esa clase de chica", autor: "Elizabeth Jane Howard", anoPublicacion: 2023, isbn: 9788419942456, portada:"https://covers.feedbooks.net/item/5672561.jpg?size=large&t=1698048124", sinopsis: "Hilary Mantel\n" +
                        "Anne y Edmund Cornhill, ambos de mediana edad, son una pareja feliz. Viven en una idílica propiedad en el campo, no muy lejos de Londres, donde él va a trabajar todos los días mientras ella se ocupa del cuidado de la casa, el jardín, la gata preñada y las deliciosas cenas para su marido. Hasta que un día, la madrastra de Edmund —la riquísima Clara, que lleva una existencia nómada y mundana— les pide que acojan a su hija Arabella, una veinteañera que se presenta en la puerta con su equipaje de ropa cara y carencias afectivas. Al no tener hijos, el matrimonio se siente de entrada inclinado a criarla, pero muy pronto su presencia resultará absolutamente desestabilizadora, revelando grietas ocultas en lo que parecía una unión indestructible…\n" +
                        "Esa clase de chica es una certera exploración de las relaciones de pareja, una lúcida mirada sobre el amor, la soledad y el deseo, esos tenues lazos que conforman el tejido de nuestras vidas.", critica: 3},
                {id: "6", nombre: "Harry Potter y la cámara secreta", autor: "J.K. Rowling", anoPublicacion: 2016, isbn: 9788498386950, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/60a007e7-31e9-439c-be44-10704c15c800/default", sinopsis: "Mientras Harry espera impaciente en casa de sus insoportables tíos el inicio del segundo curso del Colegio Hogwarts de Magia y Hechicería, un elfo aparece en su habitación y le advierte de que una amenaza mortal se cierne sobre la escuela. Harry no se lo piensa dos veces y, acompañado de Ron, se dirige a Hogwarts en un coche volador. Allí, Harry oye extraños susurros en los pasillos desiertos y, de pronto... los ataques comienzan. La siniestra predicción del elfo parece hacerse realidad.", critica: 4.3},
                {id: "7", nombre: "Danza de corazones", autor: "Nora Roberts", anoPublicacion: 2017, isbn: 9788491701736, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/fb33eca8-631a-4b36-4483-e5555e90e300/default", sinopsis: "Maddy O'Hurley era optimista, vital y divertida... y fue poco a poco metiéndose en la vida y el maltrecho corazón de Reed Valentine. Maddy estaba segura de que con un poco de paciencia y mucho amor podría hacer que Reed se enamorara de ella. Sin embargo, él no estaba dispuesto a arriesgarse... El mejor regalo para San Valentín, una novela de amor de Harlequin", critica: 3.75},
                {id: "8", nombre: "Días grises con cielo azul", autor: "Concepción Revuelta", anoPublicacion: 2021, isbn: 9788401025952, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/ba726277-205d-4dc1-c379-c628ed475000/default", sinopsis: "Tras varios años viviendo en París, Julieta regresa a Santander, la ciudad en la que pasó su infancia al cuidado de su querida tía Inés. Al llegar, se encuentra con que su tía ha sufrido un colapso de salud. Desde la cama del hospital esta le narra a su sobrina la insólita y secreta historia de su vida, plagada de viejos pecados con largas sombras. La joven Inés, que sueña con ser maestra, vive con sus hermanos y su brutal y violento padre, pero un trágico giro del destino la empujará a abandonar a su familia y comenzar una nueva vida. Primero en Santander, donde tendrá que hacerse cargo de una pensión, y más tarde como maestra en una pequeña escuela en los Picos de Europa, Inés vivirá una apasionante aventura que hará que ponga en valor la amistad y el amor; y experimentará la amargura del odio y la traición.\n" +
                        "Días grises con cielo azul es la épica historia de una mujer fuerte que nunca quiso dejarse vencer por nada ni por nadie.", critica: 4.17},
                {id: "9", name: "Chumy Restaurante, donde Jose", cuisine: "Castiza", rating: 3.6},
                {id: "10", name: "Chumy Restaurante, donde Jose", cuisine: "Castiza", rating: 3.6},
                {id: "11", name: "Chumy Restaurante, donde Jose", cuisine: "Castiza", rating: 3.6},
                {id: "12", name: "Chumy Restaurante, donde Jose", cuisine: "Castiza", rating: 3.6},
                {id: "13", name: "Chumy Restaurante, donde Jose", cuisine: "Castiza", rating: 3.6},
                {id: "14", name: "Chumy Restaurante, donde Jose", cuisine: "Castiza", rating: 3.6},
                {id: "15", name: "Chumy Restaurante, donde Jose", cuisine: "Castiza", rating: 3.6},
                {id: "16", name: "Chumy Restaurante, donde Jose", cuisine: "Castiza", rating: 3.6},
                {id: "17", name: "Chumy Restaurante, donde Jose", cuisine: "Castiza", rating: 3.6},
                {id: "18", name: "Chumy Restaurante, donde Jose", cuisine: "Castiza", rating: 3.6},
                {id: "19", name: "Chumy Restaurante, donde Jose", cuisine: "Castiza", rating: 3.6},
                {id: "20", name: "Chumy Restaurante, donde Jose", cuisine: "Castiza", rating: 3.6},
                {id: "21", name: "Chumy Restaurante, donde Jose", cuisine: "Castiza", rating: 3.6},
                {id: "22", name: "Chumy Restaurante, donde Jose", cuisine: "Castiza", rating: 3.6},
                {id: "23", name: "Chumy Restaurante, donde Jose", cuisine: "Castiza", rating: 3.6},
                {id: "24", name: "Chumy Restaurante, donde Jose", cuisine: "Castiza", rating: 3.6},
            ]);
        }, 2500);
    }, []);

    return books;
}