import {useEffect, useState} from "react";

export const useBooks = () => {

    const [books, setBooks] = useState([]);
    /**
     * Se hace uso de useEffect para definir un efecto de montaje que traerá la información de los libros
     * del back-end en el primer renderizado.
     */
    useEffect(() => {
        setTimeout(() => {
            setBooks([
                {id: "1", nombre: "Nada que decir", autor: "Silvia Hidalgo", anoPublicacion: 2023, isbn: 9788411073417, portada:"https://covers.feedbooks.net/item/5650583.jpg?size=large&t=1697156483", sinopsis: "Una mujer aguarda en el interior de un coche a que su exmarido recoja a la hija de ambos, que llora en el asiento de atrás. Mientras cae la lluvia y las figuras se desdibujan iluminadas por los intermitentes, ella está pendiente de su móvil y de una cita con un desconocido. Como un animal desorientado y furioso, se deja llevar por su deseo crudo, sin tapujos, en el que la maternidad, la familia, el trabajo ocupan un lugar secundario. Quiere huir de los espejismos de una falsa felicidad, pero se sitúa ante el abismo de una relación enfermiza, desquiciada, con un directivo de la empresa de su exmarido, un «hombre tumor».", critica: 3.5, idioma: "Castellano"},
                {id: "2", nombre: "El infiltrado", autor: "John le Carré", anoPublicacion: 2016, isbn: 9788408154983, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/764f1825-01f5-4989-4432-2515b2600400/default", sinopsis: "Al comienzo, Jonathan Pine es simplemente el director nocturno de un lujoso hotel. Pero, cuando un intento de pasar información acerca de un hombre de negocios internacionales con tratos sospechosos alojado e n el establecimiento se vuelve en su contra de una manera terrible y empiezan a morir personas cercanas a Pine, él se compromete a luchar contra unas fuerzas tan poderosas que no podría ni imaginar. En un relato escalofriante sobre corruptas agencias de inteligencia, sumas millonarias y la verdad tras el brutal comercio de armas, John le Carré crea un mundo claustrofóbico en el que no se puede confiar en nadie.", critica: 3.67, idioma: "Castellano"},
                {id: "3", nombre: "One Piece nº 001", autor: "Eiichiro Oda", anoPublicacion: 2022, isbn: 9788468471525, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/cfebd578-f0d0-4cc0-7c37-0c4aae09bc00/default", sinopsis: "Sigue las aventuras de Monkey D. Luffy, un chico muy especial y elástico, que sueña con ser el rey de los piratas y encontrar una gran tesoro: el One Piece. Para ello, se hace a la mar en un bote con el que buscará la tripulación que le pueda ayudar en su misión.\n" +
                        "Uno de los manga shônen más exitosos de la Historia, junto con Dragon Ball y Naruto. El argumento destaca valores como el espíritu superación, la tolerancia hacia la diferencia y el compañerismo. Creado por el mangaka Eiichiro Oda.", critica: 4.2, idioma: "Castellano"},
                {id: "4", nombre: "Angélique", autor: "Guillaume Musso", anoPublicacion: 2023, isbn: 9788411484213, portada:"https://covers.feedbooks.net/item/5692280.jpg?size=large&t=1698451804", sinopsis: "Un laberinto de emociones e incertidumbres del autor más vendido de Francia.Incluso los ángeles tienen sus demonios...París, Navidad de 2021.Tras sufrir un ataque al corazón, Mathias Taillefer se despierta en una habitación de hospital. A su cabecera está una joven desconocida. Se trata de Louise Collange, una estudiante que toca el violonchelo para los pacientes de forma desinteresada. Al enterarse de que Mathias es policía, le pide que retome un caso un tanto particular. Aunque al principio se resiste, Mathias acaba accediendo a prestarle ayuda y desde ese momento ambos quedan atrapados en un engranaje mortal.Así comienza una investigación fuera de lo común, cuyo secreto reside en la vida que nos habría gustado tener, el amor que podríamos haber conocido y el lugar que todavía esperamos encontrar en el mundo...", critica: 4.2, idioma: "Castellano"},
                {id: "5", nombre: "Esa clase de chica", autor: "Elizabeth Jane Howard", anoPublicacion: 2023, isbn: 9788419942456, portada:"https://covers.feedbooks.net/item/5672561.jpg?size=large&t=1698048124", sinopsis: "Hilary Mantel\n" +
                        "Anne y Edmund Cornhill, ambos de mediana edad, son una pareja feliz. Viven en una idílica propiedad en el campo, no muy lejos de Londres, donde él va a trabajar todos los días mientras ella se ocupa del cuidado de la casa, el jardín, la gata preñada y las deliciosas cenas para su marido. Hasta que un día, la madrastra de Edmund —la riquísima Clara, que lleva una existencia nómada y mundana— les pide que acojan a su hija Arabella, una veinteañera que se presenta en la puerta con su equipaje de ropa cara y carencias afectivas. Al no tener hijos, el matrimonio se siente de entrada inclinado a criarla, pero muy pronto su presencia resultará absolutamente desestabilizadora, revelando grietas ocultas en lo que parecía una unión indestructible…\n" +
                        "Esa clase de chica es una certera exploración de las relaciones de pareja, una lúcida mirada sobre el amor, la soledad y el deseo, esos tenues lazos que conforman el tejido de nuestras vidas.", critica: 3, idioma: "Castellano"},
                {id: "6", nombre: "Harry Potter y la cámara secreta", autor: "J.K. Rowling", anoPublicacion: 2016, isbn: 9788498386950, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/60a007e7-31e9-439c-be44-10704c15c800/default", sinopsis: "Mientras Harry espera impaciente en casa de sus insoportables tíos el inicio del segundo curso del Colegio Hogwarts de Magia y Hechicería, un elfo aparece en su habitación y le advierte de que una amenaza mortal se cierne sobre la escuela. Harry no se lo piensa dos veces y, acompañado de Ron, se dirige a Hogwarts en un coche volador. Allí, Harry oye extraños susurros en los pasillos desiertos y, de pronto... los ataques comienzan. La siniestra predicción del elfo parece hacerse realidad.", critica: 4.3, idioma: "Castellano"},
                {id: "7", nombre: "Danza de corazones", autor: "Nora Roberts", anoPublicacion: 2017, isbn: 9788491701736, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/fb33eca8-631a-4b36-4483-e5555e90e300/default", sinopsis: "Maddy O'Hurley era optimista, vital y divertida... y fue poco a poco metiéndose en la vida y el maltrecho corazón de Reed Valentine. Maddy estaba segura de que con un poco de paciencia y mucho amor podría hacer que Reed se enamorara de ella. Sin embargo, él no estaba dispuesto a arriesgarse... El mejor regalo para San Valentín, una novela de amor de Harlequin", critica: 3.75, idioma: "Castellano"},
                {id: "8", nombre: "Días grises con cielo azul", autor: "Concepción Revuelta", anoPublicacion: 2021, isbn: 9788401025952, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/ba726277-205d-4dc1-c379-c628ed475000/default", sinopsis: "Tras varios años viviendo en París, Julieta regresa a Santander, la ciudad en la que pasó su infancia al cuidado de su querida tía Inés. Al llegar, se encuentra con que su tía ha sufrido un colapso de salud. Desde la cama del hospital esta le narra a su sobrina la insólita y secreta historia de su vida, plagada de viejos pecados con largas sombras. La joven Inés, que sueña con ser maestra, vive con sus hermanos y su brutal y violento padre, pero un trágico giro del destino la empujará a abandonar a su familia y comenzar una nueva vida. Primero en Santander, donde tendrá que hacerse cargo de una pensión, y más tarde como maestra en una pequeña escuela en los Picos de Europa, Inés vivirá una apasionante aventura que hará que ponga en valor la amistad y el amor; y experimentará la amargura del odio y la traición.\n" +
                        "Días grises con cielo azul es la épica historia de una mujer fuerte que nunca quiso dejarse vencer por nada ni por nadie.", critica: 4.17, idioma: "Castellano"},
                {id: "9", nombre: "The Town with No Mirrors", autor: "Christina Collins", anoPublicacion: 2023, isbn: 9781492655367, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/470e68cb-ea1c-4c29-5cc1-fc38a7ffb500/default", sinopsis: "In a modern-day utopian community where mirrors, photos, and even words like beautiful and ugly are forbidden, a girl who has never seen her own face harbors a guilty curiosity about the outside world. A thoughtful exploration of self-image in a world familiar to readers of The Giver and The List.Zailey has never seen her own face. She's never seen her reflection, or a photo of herself, or even a drawing. In the special community of Gladder Hill, cameras and mirrors are forbidden: it's why everyone's happier here. Nobody talks about anyone else's appearance. You're not supposed to even think about what other people look like, or what you look like.But Zailey does.She knows her superficial thoughts are wrong, and her sketchbook, filled with secret portraits of her classmates and neighbors, could get her in trouble. Yet she can't help but think those thoughts, and be curious about the outside world where she once lived, years ago. Most of all, she wonders what it's like to see herself-her own face.When Zailey suddenly finds herself beyond the gates of her town, she has a chance to see if what she's been taught about the outside world is true and search for the mother she barely remembers. Only then will she find out the real story about Gladder Hill. But is she prepared for the truth?", critica: 4.23, idioma: "Inglés"},
                {id: "10", nombre: "Percy Jackson and the Sword of Hades", autor: "Rick Riordan", anoPublicacion: 2023, isbn: 9781368099325, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/ce584e73-c90b-4ea5-643e-0badae184c00/default", sinopsis: "In this Percy Jackson mini adventure first published in The Demigod Files, the goddess Persephone summons Percy, Thalia, and Nico to the Underworld to retrieve Hades's powerful sword before it falls into the wrong hands. Easier said than done in a realm full of daimons, ghosts, and monsters. Not to mention Iapetos-brother of the powerful Titan lord, Kronos. Will the demigods manage to find and return the sword before it's too late? Includes an excerpt from the upcoming novel The Sun and the Star: A Nico di Angelo Adventure by Rick Riordan and Mark Oshiro.", critica: 3.2, idioma: "Inglés"},
                {id: "11", nombre: "El desierto blanco", autor: "Luis López Carrasco", anoPublicacion: 2023, isbn: 9788433921635, portada:"https://covers.feedbooks.net/item/5702296.jpg?size=large&t=1701432408", sinopsis: "Nueve desconocidos huyen en globo de unos bombardeos. Deben decidir quién de ellos se tiene que tirar al mar para que el resto pueda llegar sano y salvo a una isla desierta y comenzar una nueva civilización. Los viajeros del globo son los únicos supervivientes de una guerra mundial que ha hecho desaparecer el mundo tal y como lo conocemos. Lo que está en juego, en realidad, no es el futuro de la especie humana, sino un trabajo temporal como vendedor en unos grandes almacenes.\n" +
                        "«Así era la búsqueda de empleo en 2011», podría escribir Carlos, el narrador de esta novela, que desde un futuro incierto intenta rescatar, junto con otras voces cercanas y cómplices, el mundo en el que vivió y al que, «por motivos de sobra conocidos, ya no podemos volver». Desde ese enigmático exilio, el narrador rastrea, a través de memorias aparentemente anecdóticas, las oscuras corrientes subterráneas que transformaron la vida de todas aquellas personas que conocía, llevándolas tan lejos de allí.Aunque ese primer cuarto del siglo XXI parezca un tiempo irrecuperable, quizá al narrarlo, al volverlo a contar como una ficción, Carlos pueda descifrar y redescubrir –como le recuerdan los correos cada vez más fantasiosos y delirantes de su hermano mayor– las claves de una época que parecía inmune a la fábula y la aventura, donde las únicas ficciones toleradas eran aquellas que permitían competir por un trabajo de mierda.López Carrasco ha escrito una novela excepcional sobre una generación vista desde un tiempo y un espacio ajenos; sobre unos personajes que habitan un extraño territorio que los impulsa a confrontarse con lo que fueron y lo que son. En ese viaje de ida y vuelta que es el recuerdo, sus protagonistas tratarán de reconstruir y, por tanto, de comprender las renuncias invisibles, las alianzas necesarias y las formas imprevistas de la utopía.", critica: 3.62, idioma: "Castellano"},
                {id: "12", nombre: "One Piece nº 002", autor: "Eiichiro Oda", anoPublicacion: 2022, isbn: 9788468471532, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/0fd9bbba-4acc-4106-5fb2-221ac88d1200/default", sinopsis: "El manga de la serie más pirata de la tele\n" +
                        "Monkey D. Luffy ha reclutado al primer miembro de su tripulación: Rolonoa Zoro, el espadachín de las tres espadas. Juntos quieren apoderarse del mapa de la Gran Ruta Marina, pero para eso deberán pelear contra Buggy y sus hombres. Luffy, decidido a convertirse en el rey de los piratas, se alía con Nami, una joven ladrona de tesoros.", critica: 4.19, idioma: "Castellano"},
                {id: "13", nombre: "Four Found Dead", autor: "Natalie D. Richards", anoPublicacion: 2023, isbn: 9781728215822, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/5c901eca-f7fd-433a-0294-c6ff00fd5a00/default", sinopsis: "The last show has ended, but the nightmare is just beginning.Tonight, Riverview Theaters is closing forever, the last remaining business in a defunct shopping mall. The moviegoers have left, and Jo and her six coworkers have the final shift, a shift that quickly takes a dark turn.First a stranger arrives with a chilling accusation. Then the power goes out and their manager disappears, along with the keys to the lobby doors and the theater safe, where the crew's phones are locked each shift. The crew's tension turns to terror when Jo discovers the dead body of one of her co-workers.Now their only chance to escape the murderer in their midst is through the dark, shuttered mall. With its boarded-up exits and disabled fire alarms, the complex is filled with hiding places for both pursuer and pursued. In order to survive this night, Jo and her friends must trust one another, navigate the sprawling ruins of the mall, and outwit a killer before he kills them all.", critica: 3.85, idioma: "Inglés"},
                {id: "14", nombre: "La chica de nieve", autor: "Javier Castillo", anoPublicacion: 2020, isbn: 9788466357098, portada:"https://covers.feedbooks.net/item/3245987.jpg?size=large&t=1695398727", sinopsis: "Nueva York, 1998, cabalgata de Acción de Gracias. Kiera Templeton, desaparece entre la multitud. Tras una búsqueda frenética por toda la ciudad, alguien encuentra unos mechones de pelo junto a la ropa que llevaba puesta la pequeña.\n" +
                        "En 2003, el día que Kiera habría cumplido ocho años, sus padres, Aaron y Grace Templeton, reciben en casa un extraño paquete: una cinta VHS con la grabación de un minuto de Kiera jugando en una habitación desconocida.\n" +
                        "Tras vender más de 650.000 ejemplares de sus anteriores novelas, Javier Castillo vuelve a poner en jaque la cordura con La chica de nieve, un oscuro viaje a las profundidades de Miren Triggs, una estudiante de periodismo que inicia una investigación paralela y descubre que tanto su vida como la de Kiera están llenas de incógnitas.", critica: 3.85, idioma: "Castellano"},
                {id: "15", nombre: "Cent ans après", autor: "Alberto Vázquez-Figueroa", anoPublicacion: 2020, isbn: 9788418263248, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/7c8be780-b58f-4a75-8ed7-b9219360f300/default", sinopsis: "Cent ans après l'épidémie de grippe espagnole qui tué soixante millions de personnes, nous avons une pandémie qui a conduit à une crise mondiale sans précédent.\n" +
                        "\n" +
                        "Le chaos et la pénurie ont pris le relais de la planète et il semblerait qu'il n'y a aucun moyen de sortir pendant que les êtres humains vivent prisonniers de la panique.\n" +
                        "\n" +
                        "Quel chemin faut-il prendre ? De quelles ressources disposons-nous pour surmonter?\n" +
                        "Celle-ci est l'histoire d'une famille forcée à vivre isolée et voir comment leurs liens sont cassés, mais ils retournent à souder plus fortement quand on comprend que n´importe quelle que soit la fin, elle sera moins douloureuse ou plus glorieuse si on l'attend ensemble.\n" +
                        "C'est aussi une chanson d'espoir car le désespoir peut tuer plus que tout virus.", critica: 4.13, idioma: "Francés"},
                {id: "16", nombre: "One Piece nº 003", autor: "Eiichiro Oda", anoPublicacion: 2022, isbn: 9788468471549, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/236a6ed3-f49d-4d85-1862-bf991fdcd700/default", sinopsis: "El manga de la serie más pirata de la tele\n" +
                        "Luffy, Zoro y Nami se hacen a la mar. En su primera escala encuentran a Gaimon, un pirata que desde hace veinte años protege un sorprendente tesoro, oculto en una isla desierta. Decididos a conseguir un buen barco, nuestros amigos viajan al continente. Allí conocerán a Usuff, un chico valiente pero terriblemente mentiroso y al Capitán Kuro, un pirata despiadado que prepara el golpe perfecto.", critica: 3.79, idioma: "Castellano"},
                {id: "17", nombre: "Le boulevard", autor: "Jean-François Sénéchal", anoPublicacion: 2022, isbn: 9782760968042, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/3c1042b3-bc8a-49f9-57f6-def14037b500/default", sinopsis: "Abandonné par sa mère, Chris se retrouve seul et désemparé. Heureusement, le boulevard n'est pas loin, avec ses voitures, son marché aux puces, sa salle de bowling. Dans cet univers populaire, il rencontre ceux et celles qui deviendront la famille qu'il n'a pas eue. Pour Chris, c'est le début d'une aventure qui le conduira à mieux accepter son handicap intellectuel et à revendiquer son droit au bonheur.", critica: 2.15, idioma: "Francés"},
                {id: "18", nombre: "Vagalume", autor: "Julio Llamazares", anoPublicacion: 2023, isbn: 9788420461830, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/018d4be8-ea1d-4e1b-6575-ac756e882f00/default", sinopsis: "«Tras cada ventana iluminada hay un alma semejante a nuestra alma, un náufrago del sueño y un superviviente del día que se termina o que va a empezar que está esperando que alguien le hable para responder». Un escritor recibe la noticia de la muerte del que fue su maestro como periodista y con el que, a pesar de no verse apenas ya, mantenía una amistad inquebrantable. Después del funeral, alguien le hace llegar de manera anónima un ejemplar de una novela que publicó el fallecido cuando era joven, un libro que prohibió la censura y que todos creían desaparecido. Ese hecho, junto con una serie de revelaciones posteriores, llevará de nuevo al protagonista a la ciudad donde inició su carrera como periodista para intentar descifrar el misterio que se cierne sobre la figura de su maestro y amigo.", critica: 3.56, idioma: "Castellano"},
                {id: "19", nombre: "Los Simpson y la filosofía", autor: "William Irwin", anoPublicacion: 2023, isbn: 9788417059262, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/908b5726-3533-4af6-f6da-c49030727400/default", sinopsis: "Los Simpson y la filosofía no solo es un análisis sobre la filosofía en el último gran artefacto cultural, sino también una introducción divertida pero rigurosísima a la obra de pensadores como Aristóteles, Kant, Heidegger o Sartre, entre muchos otros. Dice la leyenda que no sucede nada que no haya sucedido antes en Los Simpson. Así que si aprendemos de ellos, aprendemos del mundo.", critica: 3.1, idioma: "Castellano"},
                {id: "20", nombre: "San Manuel Bueno, mártir", autor: "Miguel de Unamuno", anoPublicacion: 2022, isbn: 9788466360258, portada:"https://covers.feedbooks.net/item/4501695.jpg?size=large&t=1649779599", sinopsis: "Una de las obras imprescindibles de Unamuno, una conmovedora historia sobre el conflicto entre la razón y la fe. Considerada por muchos el testamento espiritual de Miguel de Unamuno, esta pequeña obra maestra aborda la dialéctica entre la fe y la duda a través de la vida de un protosanto moderno llamado don Manuel, párroco de un pueblecito de la provincia de Zamora. Quien nos trasmite sus recuerdos de ese hombre excepcional es la última de sus discípulas, y su relato crea una auténtica tensión dramática gracias a la riqueza espiritual de los personajes. La guía didáctica de la presente edición, a cargo del profesor Vicente Santiago Mulas, atiende especialmente al contexto histórico y literario de la historia e incorpora los enfoques competenciales e interdisciplinares actualmente recomendados por las autoridades educativas. La crítica ha dicho:«El lector deberá atravesar diversas instancias narrativas antes de descubrir el secreto».Fernando Aramburu «Una novela de decantada madurez».Ignacio Echevarría «[De] las novelas breves […] San Manuel Bueno es la más alta y clara».María Zambrano«Cada lector, incluso cada época, ha ido mirando la obra de Unamuno según diversas perspectivas, y las imágenes de él han ido cambiando. Yo señalé que lo más importante de su obra era […] la novela, en la que veía lo más innovador y creador».Julián Marías", critica: 3.98, idioma: "Castellano"},
                {id: "21", nombre: "Florentino. Viaje hacia el Real Madrid del siglo XXI", autor: "Ramón Álvarez de Mon", anoPublicacion: 2023, isbn: 9788412572728, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/7afc2dc3-a2c1-4c7d-829d-c4df6708bf00/default", sinopsis: "Una biografía rigurosa para comprender y conocer mejor al presidente del club más importante del mundo, Florentino Pérez. Ramón Álvarez de Mon relata el recorrido de Florentino Pérez al frente del Real Madrid, poniendo especial énfasis en las distintas estrategias de las dos etapas de Florentino como presidente del club blanco y entendiendo su segunda etapa como una rectificación de los aspectos que no funcionaron del todo bien en la primera.Su gestión económica; la venta de la ciudad deportiva, la compra de Valdebebas, nuevas estrategias en la política de compra y venta de jugadores, la reforma del Santiago Bernabéu, la Superliga. En la parte social; las elecciones, el voto por correo, el adiós de leyendas del club como Hierro, Del Bosque, Raúl, Casillas o Cristiano.", critica: 4.6, idioma: "Castellano"},
                {id: "22", nombre: "One Piece nº 004", autor: "Eiichiro Oda", anoPublicacion: 2022, isbn: 9788468471556, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/e21957ef-4630-4992-8488-be4c80e5b000/default", sinopsis: "El Capitán Kuro se ha hecho pasar por el mayordomo de Kaya, la chica más rica del pueblo. Su plan consiste en atacar la aldea, matar al joven y heredar su fortuna. Luffy, Zoro y Nami saben lo que su amigo Usuff siente por Kaya; por eso deciden ayudarle y plantar cara a los piratas. Monkey D. Luffy está dispuesto a todo: ¡ésta va ser una guerra sin cuartel!", critica: 3.9, idioma: "Castellano"},
                {id: "23", nombre: "Harry Potter y el prisionero de Azkaban", autor: "J.K. Rowling", anoPublicacion: 2016, isbn: 9788498386967, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/d2da2bac-7601-41e4-f165-e30b1be07600/default", sinopsis: "De la prisión de Azkaban se ha escapado un terrible villano, Sirius Black, un asesino en serie que fue cómplice de lord Voldemort y que, dicen los rumores, quiere vengarse de Harry por haber destruido a su maestro. Por si esto fuera poco, entran en acción los dementores, unos seres abominables capaces de robarles la felicidad a los magos y de eliminar todo recuerdo hermoso de aquellos que se atreven a acercárseles. El desafío es enorme, pero Harry, Ron y Hermione son capaces de enfrentarse a todo esto y mucho más.", critica: 4.8, idioma: "Castellano"},
                {id: "24", nombre: "La extinción de los dinosaurios", autor: "Blue Planet Productions S.L.", anoPublicacion: 1990, isbn: 9788460840268, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/f0beb278-caa2-4c06-939d-8919e9e71100/default", sinopsis: "Este cuento es una historia real de un periodo en el que nuestro planeta era muy diferente a cómo ahora lo conocemos. Es una historia que fascinará a los niños, les hará imaginar, les hará pensar y, además, les enseñará uno de los momentos cumbres de la historia de la Tierra.", critica: 4.1, idioma: "Castellano"},
                {id: "25", nombre: "One Piece nº 005", autor: "Eiichiro Oda", anoPublicacion: 2022, isbn: 9788468471563, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/52d36e33-d9d4-41b2-af2a-8f25c0258100/default", sinopsis: "Luffy está descubriendo que esto de ser pirata no es nada fácil: la batalla sobre la colina ha sido dura, y aún no tiene que librar el último combate. Esta vez Luffy deberá enfrentarse en solitario al maligno Crajador. ¿O deberíamos llamarle Capitán Kuro? Mientras tanto, Zoro y Usuff se han adentrado en el bosque. Van tras la pista de Kaya y los niños, que huyen del resto de los invasores.", critica: 4.3, idioma: "Castellano"},
                {id: "26", nombre: "Nana", autor: "Émile Zola", anoPublicacion: 2019, isbn: 9788832519891, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/7fc67d20-7ae9-4899-cb27-3b6c5d344200/default", sinopsis: "Née en 1852 dans la misère du monde ouvrier, Anna Coupeau dite Nana est la fille de Gervaise Macquart et de Coupeau dont l’histoire est narrée dans L'Assommoir. Sa tentative de s'émanciper et son ascension vont bientôt se transformer en une tragédie. Nana parle du thème de la prostitution féminine à travers le parcours d’une lorette puis cocotte dont les charmes ont affolé les plus hauts dignitaires du Second Empire. Le personnage de Nana a surtout été inspiré à Zola par Blanche D'Antigny et par Berthe, son premier amour. Mais le romancier y a aussi mis des éléments de Valtesse de La Bigne, Delphine de Lizy, Anna Deslions, Hortense Schneider et Cora Pearl dont il a étudié la vie. Le roman a souvent été adapté au cinéma et au théâtre, surtout l’adaptation de Jean Renoir en 1926 et celle de Christian-Jaque (1955).", critica: 2.5, idioma: "Francés"},
                {id: "27", nombre: "Mon manuel pour le bonheur", autor: "Vicky Palacio", anoPublicacion: 2021, isbn: 9781667419534, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/b43a259d-00ed-4808-2077-2c83de1f5b00/default", sinopsis: "Le secret du bonheur est entre vos mains, ce trésor tant recherché par beaucoup qu'il semble être caché. Ce petit livre vous servira beaucoup si vous l'utilisez bien et le meilleur de tous, c'est que peu importe votre âge, si cela ne vous semble plus si cool et que vous vous sentez trop gros pour un livre plein de dessins animés, vos réponses continueront de vous aider pour la vie. Avec ce manuel, vous aurez non seulement la carte au trésor, mais aussi la clé qui ouvre le coffre, car en effectuant chacune des 37 missions, vous apprendrez la formule magique du bonheur, qui fonctionnera pour vous partout et à tout âge , parce qu'être heureux, c'est simplement être heureux.", critica: 3.45, idioma: "Francés"},
                {id: "28", nombre: "Harry Potter y la Orden del Fénix", autor: "J.K. Rowling", anoPublicacion: 2016, isbn: 9788498386981, portada:"https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/f0d8ed28-f61a-46cf-4a6b-897aca516700/default", sinopsis: "Las vacaciones de verano aún no han acabado y Harry se encuentra más inquieto que nunca. Apenas ha tenido noticias de Ron y Hermione, y presiente que algo extraño está sucediendo en Hogwarts. No bien empieza el nuevo curso, sus temores se vuelven realidad: el Ministerio de Magia ha iniciado una campaña de desprestigio contra él y Dumbledore, para lo cual ha asignado a la horrible profesora Dolores Umbridge la tarea de vigilar sus movimientos. Y por si fuera poco, Harry sospecha que Voldemort es capaz de adivinar sus pensamientos con el fin de apoderarse de un objeto secreto que le permitiría recuperar su poder destructivo.", critica: 4.13, idioma: "Castellano"},

            ]);
        }, 2500);
    }, []);

    return books;
}